# Build the static content
FROM node:latest AS build
WORKDIR /src
COPY ./Source/Gateway/Web/package.json ./Web/package.json
WORKDIR /src/Web
RUN mkdir ../Core
RUN mkdir ../Core/wwwroot
RUN yarn
RUN yarn global add webpack
RUN yarn global add webpack-cli
RUN yarn add babel-loader@7
COPY ./Source/Gateway/Web/. ./
RUN webpack -p --env.production

# Build runtime image
FROM nginx
WORKDIR /app
EXPOSE 80
COPY --from=build /src/Core/wwwroot /usr/share/nginx/html